// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: proto/shortener/request.proto

package shortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestEncode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEncode) Reset() {
	*x = RequestEncode{}
	mi := &file_proto_shortener_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEncode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEncode) ProtoMessage() {}

func (x *RequestEncode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEncode.ProtoReflect.Descriptor instead.
func (*RequestEncode) Descriptor() ([]byte, []int) {
	return file_proto_shortener_request_proto_rawDescGZIP(), []int{0}
}

func (x *RequestEncode) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RequestDecode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDecode) Reset() {
	*x = RequestDecode{}
	mi := &file_proto_shortener_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDecode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDecode) ProtoMessage() {}

func (x *RequestDecode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDecode.ProtoReflect.Descriptor instead.
func (*RequestDecode) Descriptor() ([]byte, []int) {
	return file_proto_shortener_request_proto_rawDescGZIP(), []int{1}
}

func (x *RequestDecode) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RequestShorten struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestShorten) Reset() {
	*x = RequestShorten{}
	mi := &file_proto_shortener_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestShorten) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestShorten) ProtoMessage() {}

func (x *RequestShorten) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestShorten.ProtoReflect.Descriptor instead.
func (*RequestShorten) Descriptor() ([]byte, []int) {
	return file_proto_shortener_request_proto_rawDescGZIP(), []int{2}
}

func (x *RequestShorten) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RequestSaveBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSaveBatch) Reset() {
	*x = RequestSaveBatch{}
	mi := &file_proto_shortener_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSaveBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSaveBatch) ProtoMessage() {}

func (x *RequestSaveBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSaveBatch.ProtoReflect.Descriptor instead.
func (*RequestSaveBatch) Descriptor() ([]byte, []int) {
	return file_proto_shortener_request_proto_rawDescGZIP(), []int{3}
}

func (x *RequestSaveBatch) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type RequestDeleteURLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeleteURLs) Reset() {
	*x = RequestDeleteURLs{}
	mi := &file_proto_shortener_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeleteURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteURLs) ProtoMessage() {}

func (x *RequestDeleteURLs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteURLs.ProtoReflect.Descriptor instead.
func (*RequestDeleteURLs) Descriptor() ([]byte, []int) {
	return file_proto_shortener_request_proto_rawDescGZIP(), []int{4}
}

func (x *RequestDeleteURLs) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

var File_proto_shortener_request_proto protoreflect.FileDescriptor

var file_proto_shortener_request_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21,
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x21, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x22, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3f, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x61, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2b, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x32, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x42, 0x42, 0x5a,
	0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x6d, 0x61,
	0x6e, 0x70, 0x31, 0x39, 0x38, 0x39, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_shortener_request_proto_rawDescOnce sync.Once
	file_proto_shortener_request_proto_rawDescData []byte
)

func file_proto_shortener_request_proto_rawDescGZIP() []byte {
	file_proto_shortener_request_proto_rawDescOnce.Do(func() {
		file_proto_shortener_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_request_proto_rawDesc), len(file_proto_shortener_request_proto_rawDesc)))
	})
	return file_proto_shortener_request_proto_rawDescData
}

var file_proto_shortener_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_shortener_request_proto_goTypes = []any{
	(*RequestEncode)(nil),     // 0: proto.shortener.RequestEncode
	(*RequestDecode)(nil),     // 1: proto.shortener.RequestDecode
	(*RequestShorten)(nil),    // 2: proto.shortener.RequestShorten
	(*RequestSaveBatch)(nil),  // 3: proto.shortener.RequestSaveBatch
	(*RequestDeleteURLs)(nil), // 4: proto.shortener.RequestDeleteURLs
	(*Item)(nil),              // 5: proto.shortener.Item
}
var file_proto_shortener_request_proto_depIdxs = []int32{
	5, // 0: proto.shortener.RequestSaveBatch.items:type_name -> proto.shortener.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shortener_request_proto_init() }
func file_proto_shortener_request_proto_init() {
	if File_proto_shortener_request_proto != nil {
		return
	}
	file_proto_shortener_entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_request_proto_rawDesc), len(file_proto_shortener_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_shortener_request_proto_goTypes,
		DependencyIndexes: file_proto_shortener_request_proto_depIdxs,
		MessageInfos:      file_proto_shortener_request_proto_msgTypes,
	}.Build()
	File_proto_shortener_request_proto = out.File
	file_proto_shortener_request_proto_goTypes = nil
	file_proto_shortener_request_proto_depIdxs = nil
}
